["auburn brown","leather","patent finish","pointed toe","branded leather insole"]
["navy blue","cotton","denim","off-shoulder","crystal embellishment","corset style"]
["cardinal red","fitted waist","self-tie belt","sleeveless"]
["orange","patent leather finish","curved heel","thong design","slim straps"]
["black","Crescent Moon","elasticated waistband"]
["bright red","stretch-design","logo print","to the front U-neck","thin shoulder","straps open back"]
["olive green","tie neck","sleeveless","patch pockets","gold buttons"]
["purple","spread collar","short sleeves","contrasting border","flared skirt"]
["black","classic hood","drop shoulder","ribbed cuffs and hem"]
["black","ruffled collar","button fastening","flared cuffs","pleated back"]
["moss green","concealed front zip fastening","chest patch pocket","buttoned cuffs","high-low hem"]
["indigo blue","front button and zip fastening","classic five pockets","logo patch to the rear"]
["blue","long sleeves","ribbed cuffs","crew neck","natural cotton"]
["silver-tone","push-lock fastening","engraved logo"]